import './globals.css'
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import Notification from "@/components/Notification"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Notification />
        <Navbar />
        {children}
        <Footer />        
      </body>
    </html>
  )
}

